#docker-compose.yml
version: "3.8" # composeファイルのバージョン
services:
  app: # サービス名
    container_name: go_learn
    build: #Dockerfileの場所
      context: docker
      dockerfile: app.Dockerfile
    tty: true # コンテナの永続化
    volumes:
      - ./app:/go/src/app # マウントディレクトリ
